### ISSUE TITLE
tableau-confluence-plugin upgrade

### ISSUE THREAD

**Issue by avenkatach** [schubergphilis/tableau-confluence-plugin#8]
Hi All,
This addon has not been upgraded and shows incompatible for Confluence Datacenter versions.
Is there any plan to upgrade the addon and have it supported for the latest confluence versions?
--Thanks in Advance
--Ajay

**Comment by iheitlager** [comment]
We advise to just try it.

This plugin generates a one time token serverside. That token is used client side to access Tableau with direct access from the browser. If  the authentication chain breaks, due to incompatibilities, security is ensured by Tableau. Just test the plugin in your combination and let us know which versions of Tableau and Confleunce you are using, please.

**Comment by avenkatach** [comment]
Hi iheitlager,
Thanks for the update. We are on :;
Confluence : 6.6.2  (DataCenter)
Tableau:  10.4

---Ajay
